### ISSUE TITLE
Lecture des  articles

### ISSUE THREAD

**Issue by ekebal** [jimmymunoz/extractiondeworkflow#1]

**Comment by jimmymunoz** [comment]
Extraction de workflow (diagramme d’activités) par l’analyse
statique du code source orienté objet.
L’objectif est d’analyser le code source d’une application orientée objet en JAVA et
d’extraire le workflow (diagramme d’activités) de cette application. Pour information
ce diagramme peut être utile pour la compréhension du comportement de
l’application ou pour l’optimisation de son dépliement sur le cloud.
La méthode d’extraction du workflow est disponible sur le lien : 

http://www.lirmm.fr/~seriai/uploads/Enseignement/workflow1.pdf
http://www.lirmm.fr/~seriai/uploads/Enseignement/projetsHmin306.pdf
